
services:
  mypostgre:
    image: postgres:16.4-alpine3.20
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
    networks:
      - my-network

networks:
  # The presence of these objects is sufficient to define them
  my-network: {}